#!/bin/sh
set -e
set -x

AUTO_DEPLOY_WEB_HOOK_PORT=${AUTO_DEPLOY_WEB_HOOK_PORT:"14000"}
AUTO_DEPLOY_WEB_HOOK_HASHKEY=${AUTO_DEPLOY_WEB_HOOK_HASHKEY:""}
GITHUB_REMOTE_ADDR=${GITHUB_REMOTE_ADDR:-}
IS_NPM_INSTALL=${IS_NPM_INSTALL:false}

cd /root/blog

if [ ! -d "/root/blog/.git" ];then
    git init
fi

if [ -z `git remote -v | grep fetch` ] ; then
 git remote add origin "$GITHUB_REMOTE_ADD"
fi

if [ ! -f "/root/.ssh/id_rsa" ] ; then
  ssh-keygen -t rsa -f ~/.ssh/id_rsa -P
  rm -rf authorized_keys
  cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
  `cat /root/.ssh/authorized_keys` 
  echo "Please copy above key to github deploy key,then continue"
  read -t 10 -p "Press Return Key to continue........"||break

if [ ! -f "/root/blog/package.json" ];then
    git pull
    npm install
    npm install hexo-generator-sitemap --save 
    npm install hexo-generator-feed --save 
    npm install hexo-deployer-git --save                     npm un hexo-renderer-marked --save 
    npm i hexo-renderer-markdown-it --save
fi

if ["IS_NPM_INSTALL"];then
    npm install
fi

if [ -f "/root/deploy.js" ]; then
   sed -i 's/{{WEB_HOOK_HASH_KEY}}/"$AUTO_DEPLOY_WEB_HOOK_HASHKEY"/g' /root/deploy.js  
   sed -i 's/{{PORT}}/"$AUTO_DEPLOY_WEB_HOOK_PORT"/g' /root/deploy.js  
fi

exec supervisord -c /etc/supervisor/supervisord.conf
