#!/bin/sh
set -e
set -x

GITHUB_DEPLOY_KEY=${GITHUB_DEPLOY_KEY:-}
HEXO_THEME=${HEXO_THEME:-}
AUTO_DEPLOY_WEB_HOOK_PORT=${AUTO_DEPLOY_WEB_HOOK_PORT:"14000"}
AUTO_DEPLOY_WEB_HOOK_HASHKEY=${AUTO_DEPLOY_WEB_HOOK_HASHKEY:""}

if [ -f "/root/deploy.js" ]; then
   sed -i 's/{{WEB_HOOK_HASH_KEY}}/"$AUTO_DEPLOY_WEB_HOOK_HASHKEY"/g' /root/deploy.js  
   sed -i 's/{{PORT}}/"$AUTO_DEPLOY_WEB_HOOK_PORT"/g' /root/deploy.js  
fi

if [ ! -z "$THEME" ]; then

case $THEME:
    "NEXT") echo "hello,next theme";;
    *) echo "default theme!";;

esac

fi

exec supervisord -c /etc/supervisor/supervisord.conf
