#!/bin/sh
set -e
set -x

AUTO_DEPLOY_WEB_HOOK_PORT=${AUTO_DEPLOY_WEB_HOOK_PORT:-"14000"}
AUTO_DEPLOY_WEB_HOOK_HASHKEY=${AUTO_DEPLOY_WEB_HOOK_HASHKEY:-""}
GITHUB_REMOTE_ADDR=${GITHUB_REMOTE_ADDR:-}
IS_NPM_INSTALL=${IS_NPM_INSTALL:-"false"}
GITHUB_BRANCH=${GITHUB_BRANCH:-"master"}

cd /root/blog

if [ ! -d "/root/blog/.git" ];then
    git init
fi

if [ ! -d "/root/auto_publish" ];then
  mkdir /root/auto_publish -p
  mv /root/deploy.js /root/auto_publish/deploy.js
  npm install github-webhook-handler --save
fi


if [ -z `git remote show` ] ; then
  echo "start setting hexo blog github address"
  git remote add origin "${GITHUB_REMOTE_ADDR}"
fi

if [ ! -f "/root/.ssh/id_rsa" ] ; then
  ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  rm -rf authorized_keys
  #cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
  cat /root/.ssh/id_rsa.pub 
  echo "Please copy above key to github deploy key,then continue"
  sleep 60s
  # read -p "Press Return Key to continue........" yes
fi

if [ ! -f "/root/blog/package.json" ];then
    git pull origin master
    npm install
    npm install hexo-generator-sitemap --save 
    npm install hexo-generator-feed --save 
    npm install hexo-deployer-git --save
    npm un hexo-renderer-marked --save 
    npm i hexo-renderer-markdown-it --save
fi

if [ "${IS_NPM_INSTALL}"x = "true"x ]; then
    npm install
fi

if [ -f "/root/auto_publish/deploy.js" ]; then
    cd /root/auto_publish
    npm install github-webhook-handler --save
    sed -i -e"s/{{WEB_HOOK_HASH_KEY}}/'${AUTO_DEPLOY_WEB_HOOK_HASHKEY}'/g" /root/auto_publish/deploy.js  
    sed -i -e"s/{{PORT}}/${AUTO_DEPLOY_WEB_HOOK_PORT}/g" /root/auto_publish/deploy.js  
fi

if [ -f "/root/build.sh" ]; then
    cd /root
    sed -i -e"s/{{BRANCH}}/${GITHUB_BRANCH}/g" /root/build.sh  
fi

exec supervisord -c /etc/supervisor/supervisord.conf
